language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database cncs;' -U postgres
script:
  - python manage.py test
env:
  - ENV=travis DB_DATABASE=cncs DB_USER=postgres DB_PASSWORD=