language: python
services:
  - docker
python:
  - "3.8"
before_install:
  - cp .env.example .env
  - docker-compose up -d
  - docker-compose exec web python manage.py migrate
script:
  - docker-compose exec web python manage.py test
env:
  - DOCKER_COMPOSE_VERSION=1.4.2