# Generated by Django 3.0.6 on 2020-06-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
